esphome:
  name: dtsu666-udp-gateway
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

external_components:
  - source: github://szsz/esphome-dtsu666-udp
    components: [dtsu666_udp_listener]

dtsu666_udp_listener:
  id: dtsu
  port: 1024
  device_id: 1     # omit to accept any device id
  pt:
    name: "DTU Combined Active Power"
  pa:
    name: "Phase A Active Power"
  pb:
    name: "Phase B Active Power"
  pc:
    name: "Phase C Active Power"
  qt:
    name: "DTU Combined Reactive Power"
  qa:
    name: "Phase A Reactive Power"
  qb:
    name: "Phase B Reactive Power"
  qc:
    name: "Phase C Reactive Power"
